<?xml version="1.0" encoding="utf-8" standalone="no"?>
<xs:schema elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns:fac="http://datex2.eu/schema/3/facilities" version="3.7" targetNamespace="http://datex2.eu/schema/3/facilities" xmlns:com="http://datex2.eu/schema/3/common" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import namespace="http://datex2.eu/schema/3/common" schemaLocation="DATEXII_3_Common.xsd" />
  <xs:complexType name="_FacilityObjectVersionedReference">
    <xs:complexContent>
      <xs:extension base="com:VersionedReference">
        <xs:attribute name="targetClass" type="xs:string" use="required" fixed="fac:FacilityObject" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:complexType name="_OpeningStatusEnum">
    <xs:simpleContent>
      <xs:extension base="fac:OpeningStatusEnum">
        <xs:attribute name="_extendedValue" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="FacilityObjectStatus">
    <xs:annotation>
      <xs:documentation>Dynamic status information for a facility object.</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="reference" type="fac:_FacilityObjectVersionedReference" minOccurs="1" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Reference to the corresponding static facility object.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="lastUpdated" type="com:DateTime" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>Information on the time when the information has been updated the last time</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="openingStatus" type="fac:_OpeningStatusEnum" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>The opening status of this facility (open or not).</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="statusDescription" type="com:MultilingualString" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>A description for the status of this facility.</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="_facilityObjectStatusExtension" type="com:_ExtensionType" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="FacilityStatus">
    <xs:annotation>
      <xs:documentation>Dynamic status information for a facility.</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="fac:FacilityObjectStatus">
        <xs:sequence>
          <xs:element name="_facilityStatusExtension" type="com:_ExtensionType" minOccurs="0" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:simpleType name="OpeningStatusEnum">
    <xs:annotation>
      <xs:documentation>The opening status of some entity (e.g. parking site, service facility, access,...)</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="open">
        <xs:annotation>
          <xs:documentation>Open resp. available.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="openWithServiceLimitation">
        <xs:annotation>
          <xs:documentation>Open, but with limited services.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="closed">
        <xs:annotation>
          <xs:documentation>Closed, usually because of the regular opening times.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="closedOnHoliday">
        <xs:annotation>
          <xs:documentation>Closed because of a holiday or holidays.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="closedOnMaintenance">
        <xs:annotation>
          <xs:documentation>Closed because of maintenance activities.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="temporarilyClosed">
        <xs:annotation>
          <xs:documentation>Temporarily closed.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="statusUnknown">
        <xs:annotation>
          <xs:documentation>The opening status is unknown.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="other">
        <xs:annotation>
          <xs:documentation>Other.</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
      <xs:enumeration value="_extended" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>